### ISSUE TITLE
Add default `edit-link` and `delete-link` css classes

### ISSUE THREAD

**Issue by colanconnon** [level12/webgrid#48]
Keg-Auth users grid depends on the `edit-link` and `delete-link` classes, but no default CSS is supplied for them. Without any css it's hard to tell that the actions are there. I added these CSS classes to make the actions work as expected.

```css
.edit-link:before {
    position: relative;
    padding: 2px;
    font-family: "FontAwesome";
    content: "\f040";
}

.delete-link:before {
    position: relative;
    padding: 2px;
    font-family: "FontAwesome";
    content: "\f1f8";
}
```
