### ISSUE TITLE
Consider reducing number of appveyor jobs

### ISSUE THREAD

**Issue by rsyring** [level12/webgrid#55]
Is it necessary to test the base and i18n versions of the tests for every Python version for both 32 and 64 bit Pythons?  This results in 12 runs of the test suite.

Unless we have code that changes based on architecture, it seems like we could cut down on the permutations here with something like I did in Keg:

```yaml
  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    - PYTHON: "C:\\Python27"
      TOXENV: py27-{base,lowest,i18n}

    - PYTHON: "C:\\Python35"
      TOXENV: py35

    - PYTHON: "C:\\Python36"
      TOXENV: py36

    - PYTHON: "C:\\Python37"
      TOXENV: py37-{base,lowest,i18n}
```

Make the permutation runs on the version bookends and keep the stuff in the middle only testing the base run.
